### PR TITLE
Upgrade deps and ignore errors

### PR DESCRIPTION
**Pull request by cmin764**
Inlines this with code with: https://github.com/robocorp/example-dialogs-google-image-search

Also upgrades _conda.yaml_ to targeted in-test deps.

### CODE REVIEW

**Comment by cmin764** [comment]
Tested in [CI](https://ci.robocloud.dev/robocorp/robocorp/processes/d6f97fd0-671d-4726-a651-128f85fc03d8/runs/81d252cd-ace1-4a47-a866-9dac07c6d864/stepRuns/032b40a8-e419-48f2-a16d-f280d9a6557d).
Screenshot 2022-06-21 at 11 12 30

**Comment by bendersej** [comment]
What about using the same logic update as [in this PR](https://github.com/robocorp/example-dialogs-google-image-search/pull/2/files#diff-5d34fe412434df7d0fbe89c219f9b80fb53a8e6f66de84ca5f4c689c62ddfe63R25)

So that instead of silently erroring, we still close the popup (and stick to the same implementation)

**Review by bendersej — APPROVED** [review]
LGTM!

**Comment by cmin764** [comment]
> What about using the same logic update as [in this PR](https://github.com/robocorp/example-dialogs-google-image-search/pull/2/files#diff-5d34fe412434df7d0fbe89c219f9b80fb53a8e6f66de84ca5f4c689c62ddfe63R25)
> 
> So that instead of silently erroring, we still close the popup (and stick to the same implementation)

I've seen the idiom of doing both:
- Clicking elements if visible only
- Guarding the above from errors (this is what we've missed from this repo, thing we already had present in the other one referenced here)

**Pull request merged**
